# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(681, 221)
        self.btnPot = QtWidgets.QPushButton(Form)
        self.btnPot.setGeometry(QtCore.QRect(20, 20, 93, 28))
        self.btnPot.setObjectName("btnPot")
        self.btnComputador = QtWidgets.QPushButton(Form)
        self.btnComputador.setGeometry(QtCore.QRect(20, 60, 93, 28))
        self.btnComputador.setObjectName("btnComputador")
        self.btnSecuencia = QtWidgets.QPushButton(Form)
        self.btnSecuencia.setGeometry(QtCore.QRect(20, 100, 93, 28))
        self.btnSecuencia.setObjectName("btnSecuencia")
        self.btGuardar = QtWidgets.QPushButton(Form)
        self.btGuardar.setGeometry(QtCore.QRect(530, 30, 93, 28))
        self.btGuardar.setObjectName("btGuardar")
        self.btnBorrar = QtWidgets.QPushButton(Form)
        self.btnBorrar.setGeometry(QtCore.QRect(530, 70, 93, 28))
        self.btnBorrar.setObjectName("btnBorrar")
        self.txtDatos = QtWidgets.QLineEdit(Form)
        self.txtDatos.setGeometry(QtCore.QRect(150, 40, 291, 22))
        self.txtDatos.setObjectName("txtDatos")
        self.btnEnviar = QtWidgets.QPushButton(Form)
        self.btnEnviar.setGeometry(QtCore.QRect(250, 70, 93, 28))
        self.btnEnviar.setObjectName("btnEnviar")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(150, 110, 21, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(150, 130, 21, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(300, 110, 21, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(300, 130, 21, 16))
        self.label_4.setObjectName("label_4")
        self.lblS1 = QtWidgets.QLabel(Form)
        self.lblS1.setGeometry(QtCore.QRect(180, 110, 91, 16))
        self.lblS1.setText("")
        self.lblS1.setObjectName("lblS1")
        self.lblS2 = QtWidgets.QLabel(Form)
        self.lblS2.setGeometry(QtCore.QRect(170, 130, 121, 16))
        self.lblS2.setText("")
        self.lblS2.setObjectName("lblS2")
        self.lblS3 = QtWidgets.QLabel(Form)
        self.lblS3.setGeometry(QtCore.QRect(330, 110, 91, 16))
        self.lblS3.setText("")
        self.lblS3.setObjectName("lblS3")
        self.lblS4 = QtWidgets.QLabel(Form)
        self.lblS4.setGeometry(QtCore.QRect(330, 130, 121, 16))
        self.lblS4.setText("")
        self.lblS4.setObjectName("lblS4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(540, 130, 55, 16))
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(540, 180, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.txtPuerto = QtWidgets.QLineEdit(Form)
        self.txtPuerto.setGeometry(QtCore.QRect(530, 150, 113, 22))
        self.txtPuerto.setObjectName("txtPuerto")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btnPot.setText(_translate("Form", "Potenciometro"))
        self.btnComputador.setText(_translate("Form", "Computador"))
        self.btnSecuencia.setText(_translate("Form", "Secuencia"))
        self.btGuardar.setText(_translate("Form", "Guardar "))
        self.btnBorrar.setText(_translate("Form", "Borrar"))
        self.btnEnviar.setText(_translate("Form", "Enviar"))
        self.label.setText(_translate("Form", "S1:"))
        self.label_2.setText(_translate("Form", "S2:"))
        self.label_3.setText(_translate("Form", "S3:"))
        self.label_4.setText(_translate("Form", "S4:"))
        self.label_5.setText(_translate("Form", "Puerto:"))
        self.pushButton.setText(_translate("Form", "Conectar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
